services:
  java-app:
    container_name: java-app
    image: df-java-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=jdbc:postgresql://java_db:5432/ticket-db
      - DB_USER=postgres
      - DB_PASSWORD=admin
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=ticket-db